### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by sovanyio** [anthropos9/ppe#1]
Hey there, not an issue per-se but didn't see an email to message you on. 
First, thanks for this! I just made the same transition and this was a lucky find :) I thought I was going to have to write an insane sql query against the sqlite db from the mobile app.

Curious how the images are intended to be used, I ended up manually assigning them in Plan To Eat, after zipping the output folder didn't associate on their end. Is that expected or did I miss something on the import in PTE?

**Comment by anthropos9** [comment]
It's unfortunate that PTE doesn't provide a way to include images in the bulk importer. I had to manually update all the images as well. My idea was more about having access to the images locally rather than having to go to every recipe in PP and download the image.

Hope it worked well for you. I didn't expect anyone to ever use it, but I figured putting it out there was worth it if someone used it.

**Comment by sovanyio** [comment]
I ended up emailing them about it and it looks like they have support via the text format, if anyone in the future wants to add support

```
The best support that we offer for importing images when using our bulk import feature is to use the Photo Url in the Bulk Import feature! There is a line within the file where you can add that URL (I have attached a screenshot of what this looks like). 
```

Screen shows:
```
Photo Url: https://www.url-for-recipe-photo.com/image/recipe-photo.jpg
```

**Comment by anthropos9** [comment]
That's brilliant. I'll have to check, but I wonder if the Pepperplate images are login restricted or if they're publicly available. Thanks for doing that research.

**Comment by madsnedergaard** [comment]
In case anyone else needs this, I'll just add that Pepperplate images are not login restricted, so this should be doable. I haven't yet decided on what platform I'm migrating to, but if I need it I'll change the code and create a pull request :)

**Comment by anthropos9** [comment]
Thanks for doing that research. If I have time I'll make some changes to the import twig file to include the image URL.
